In [3]:
import torch
import numpy as np

In [4]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [5]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [16]:
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [10]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [11]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.1975, 0.6985],
        [0.9259, 0.1634]]) 



In [12]:
shape = (2,3,)
zeros_tensor = torch.zeros(shape)
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [15]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


In [17]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [22]:
tensor = torch.ones(4,4)
print(f"Last column: {tensor[..., -1]}")
print(tensor)

Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [23]:
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [24]:
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])


In [25]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1 == y2)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
// @ matrix multiplication, * element-wise product